[workspace]
authors = ["tonyfast <tony.fast@uw.edu>"]
channels = ["conda-forge"]
name = "a11yhood-backend"
platforms = ["osx-arm64"]
version = "0.1.0"

[environments]
test = {features = ["test", "default"] }

[feature.test.tasks.run-tests]
description = "run the test suite"
cmd = "pytest"


[tasks.run-dev]
description = "run the application in development mode"
cmd = "ENVIRONMENT=development python -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4"

[tasks.run-dev.env]
DATABASE_URL = "sqlite:///./test.db"

[dependencies]
python = ">=3.14.3,<3.15"
pip = ">=26.0.1,<27"
aiosqlite = ">=0.22.1,<0.23"
anyio = ">=4.12.1,<5"
pytest-asyncio = ">=1.3.0,<2"

[pypi-dependencies]
annotated-doc = ">=0.0.4, <0.0.5"
aiosqlite = "*"
annotated-types = ">=0.7.0, <0.8"
anyio = "*"
apscheduler = ">=3.11.2, <4"
beautifulsoup4 = ">=4.14.3, <5"
bleach = ">=6.3.0, <7"
cachetools = ">=6.2.6, <7"
certifi = ">=2026.1.4, <2027"
cffi = ">=2.0.0, <3"
charset-normalizer = ">=3.4.4, <4"
click = ">=8.3.1, <9"
cryptography = ">=46.0.5, <47"
deprecated = ">=1.3.1, <2"
deprecation = ">=2.1.0, <3"
fastapi = ">=0.129.0, <0.130"
fsspec = ">=2026.2.0, <2027"
h11 = ">=0.16.0, <0.17"
h2 = ">=4.3.0, <5"
hpack = ">=4.1.0, <5"
httpcore = ">=1.0.9, <2"
httptools = ">=0.7.1, <0.8"
httpx = ">=0.28.1, <0.29"
hyperframe = ">=6.1.0, <7"
idna = "*"
limits = ">=5.8.0, <6"
lxml = ">=6.0.2, <7"
markdown-it-py = ">=4.0.0, <5"
mdurl = ">=0.1.2, <0.2"
mmh3 = ">=5.2.0, <6"
multidict = ">=6.7.1, <7"
oauthlib = ">=3.3.1, <4"
packaging = ">=26.0, <27"
postgrest = ">=2.28.0, <3"
propcache = ">=0.4.1, <0.5"
pycparser = ">=3.0, <4"
pydantic = ">=2.12.5, <3"
pydantic-core = ">=2.41.5, <3"
pydantic-settings = ">=2.13.0, <3"
pygments = ">=2.19.2, <3"
pyiceberg = ">=0.11.0, <0.12"
pyjwt = ">=2.11.0, <3"
pyparsing = ">=3.3.2, <4"
pyroaring = ">=1.0.3, <2"
python-dateutil = ">=2.9.0.post0, <3"
python-dotenv = ">=1.2.1, <2"
python-multipart = ">=0.0.22, <0.0.23"
pyyaml = ">=6.0.3, <7"
realtime = ">=2.28.0, <3"
requests = ">=2.32.5, <3"
requests-oauthlib = ">=2.0.0, <3"
rich = ">=14.3.2, <15"
six = ">=1.17.0, <2"
slowapi = ">=0.1.9, <0.2"
sortedcontainers = ">=2.4.0, <3"
soupsieve = ">=2.8.3, <3"
sqlalchemy = ">=2.0.46, <3"
starlette = ">=0.52.1, <0.53"
storage3 = ">=2.28.0, <3"
strenum = ">=0.4.15, <0.5"
strictyaml = ">=1.7.3, <2"
supabase = ">=2.28.0, <3"
supabase-auth = ">=2.28.0, <3"
supabase-functions = ">=2.28.0, <3"
tenacity = ">=9.1.4, <10"
typing-extensions = "*"
typing-inspection = ">=0.4.2, <0.5"
tzlocal = ">=5.3.1, <6"
urllib3 = ">=2.6.3, <3"
uvicorn = ">=0.41.0, <0.42"
uvloop = ">=0.22.1, <0.23"
watchfiles = ">=1.1.1, <2"
webencodings = ">=0.5.1, <0.6"
websockets = ">=15.0.1, <16"
wrapt = ">=2.1.1, <3"
yarl = ">=1.22.0, <2"

[feature.test.dependencies]
pytest = "*"
